### ISSUE TITLE
Create schema via GraphQL

### ISSUE THREAD

**Issue by jamilabreu** [liveforeverx/dlex#107]
I can see how to create schema via alter using N-Quad notation, but not how to do it w/ GraphQL notation as outlined here:

https://dgraph.io/docs/graphql/admin/

Happy to help upgrade the docs here if needed!

**Comment by benregn** [comment]
Did you figure it out? I guess you've also solved the authentication with Slash GraphQL? I got stuck just trying to connect to my Slash GraphQL instance using dlex.

**Comment by jamilabreu** [comment]
@benregn You can use a normal http client (I use https://github.com/keathley/finch, but lots of people use https://github.com/edgurgel/httpoison) to send graphql requests.

I haven't connected it yet, but did you add this to `config/prod.exs`:

```
// replace XXXXX with slash graphql endpoint subdomain
config :appname, AppName.Repo, hostname: "https://XXXXXX.cloud.dgraph.io"
```

**Comment by jamilabreu** [comment]
I can't get it to work either :\ Lmk if you do!
