### ISSUE TITLE
.get! throws error with master branch

### ISSUE THREAD

**Issue by goravbhootra** [liveforeverx/dlex#46]
Repo.get!("0x7") `<- this uid exists in db, connection info is passed through repo.ex`

throws following error:
```** (ArgumentError) raise/1 and reraise/2 expect a module name, string or exception as the first argument, got: {:untyped, %{"courses.description" => "testing the course", "courses.duration_units" => 3, "courses.title" => "Refresher Course", "dgraph.type" => ["type.courses"], "uid" => "0x7"}}```

It works fine with this [commit](https://github.com/liveforeverx/dlex/tree/b8e8b84af8d19c61b2369dd5dacc53e226887ba5)

**Comment by liveforeverx** [comment]
@goravbhootra Hi! Thank you for reporting!

Can you provide a test, which I can integrate?

**Comment by liveforeverx** [comment]
Ah, I think I know. The last change wasn't backwards compatible, it changed how the type is named. Now it isn't `type.courses`, but it is `courses`.

You need manually rename it to `courses` in dgraph or change a schema to be `type.courses`.

**Comment by liveforeverx** [comment]
Sorry for this, I forgot to mention in Changelog, that it is backwards-incompatible

**Comment by goravbhootra** [comment]
Thanks for the response. I have fixed the issue at my end.

I think there is a typo. You have mentioned above `backwards-incompatible` but Changelog mentions `Backwards-compatible changes:`

**Comment by liveforeverx** [comment]
@goravbhootra Thank you for mentions the type, will change on next commit!
