### ISSUE TITLE
Usage across app

### ISSUE THREAD

**Issue by felixakiragreen** [liveforeverx/dlex#5]
Thanks for releasing this library!

Just looking for a little clarification, and forgive me because I've been using Elixir for ~6 months.

Is there a way to `Dlex.start_link` in one location and then get the `pid` anywhere it's needed through the app? Or is the recommended approach to use `Dlex.start_link` in each function where queries/mutation are needed?

For example, I tried doing this in my application.ex:
```
def start(_type, _args) do
    children = [
      # ...
      {Dlex, [name: :dlex]},
    ]
```
And then doing
`{:ok, result} = Dlex.query(:dlex, query)` in other modules, but that produces a bunch of Run time errors. 

I did see that the tests do something to this effect by using `setup` and passing in the pid/(conn) to each test, but I'm wanting know if this can be done for the whole application across multiple contexts.

Thanks again!

**Comment by liveforeverx** [comment]
Hi! `name` should work:

```elixir
iex(2)> Dlex.start_link(name: :test)
{:ok, #PID<0.222.0>}
iex(3)>  Dlex.query!(:test, "query all($a: string) {all(func: eq(name, $a)) {uid frind { name } expand(_all_)}}", %{"$a" => "alice"})
%{"all" => []}
```

Please, add your stacktrace, probably there is unrelated error.

**Comment by liveforeverx** [comment]
Please reopen issue with an error. Thank you!

**Comment by felixakiragreen** [comment]
@liveforeverx I finally figured out what I was trying to ask.

How do I start Dlex as a Supervised process? I can confirm `name` does work. But when I try to start it as a child of a supervisor, I get these errors:
```
[error] GenServer #PID<0.402.0> terminating
** (RuntimeError) connect raised ArgumentError exception.The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true if you wish to see all of the details
    :erlang.binary_to_integer/1
    (grpc) lib/grpc/stub.ex:114: GRPC.Stub.connect/3
    (dlex) lib/dlex/protocol.ex:22: Dlex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:66: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Dlex.Protocol
```

**Comment by liveforeverx** [comment]
@xenophilicibex Thank you, child_spec (for supervisor) didn't include default localhost and port for connection, so that is a reason, why it crashed. Fixed in `0.1.1` (available in hex too).

**Comment by liveforeverx** [comment]
Otherwise it should work, as you have initially tried:

```elixir
children = [
      # ...
      {Dlex, [name: :dlex]},
    ]
```

**Comment by felixakiragreen** [comment]
It's working now, thank you!
