### ISSUE TITLE
set() and mutate() with Ecto Changesets results in error

### ISSUE THREAD

**Issue by martinthenth** [liveforeverx/dlex#71]
I get the error `no function clause matching in MyApp.Post.__schema__/2` when using `Repo.set()` with an Ecto Changeset. 

Steps to reproduce: 
1. Create changeset: `changeset = Post.create_changeset(Post{}, params)`.
2. Insert changeset: `Repo.set(changeset)`.
3. Error `no function clause matching in MyApp.Post.__schema__/2` is received.
Dlex supports inserting changesets via 
`def mutate(conn, %{__struct__: Ecto.Changeset, changes: changes, data: %type{uid: uid}}, opts) do
    data = struct(type, Map.put(changes, :uid, uid))
    mutate(conn, data, opts)
  end` 

I made a pull request in #70 that solves this issue.

**Comment by liveforeverx** [comment]
Thank you!
